name: Slack notification

on:
  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: notify slack in case of success
        id: slack_success
        uses: slackapi/slack-github-action@v1.24.0
        # https://api.slack.com/apps/<your-app-id>/incoming-webhooks
        if: ${{ success() }}
        with:
          channel-id: 'C07HE9MMNKC' # slack channel #notications
          payload: |
            {
              "text": "Successful GitHub Action",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn", 
                    "text": "*Successful deployment* :white_check_mark:\n *User:* ${{ github.actor }}  *Branch:* ${{ github.ref }}  *Repo:* ${{ github.repository }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":link: Successful action"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: notify slack in case of failure
        id: slack_failure
        uses: slackapi/slack-github-action@v1.24.0
        # https://api.slack.com/apps/<your-app-id>/incoming-webhooks
        if: ${{ failure() }}
        with:
          channel-id: 'C07HE9MMNKC' # slack channel #notications
          payload: |
            {
              "text": "GitHub Action failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Deployment failed* :fire_engine:\n User: ${{ github.actor	}} Branch: ${{ github.ref	}} Repo: ${{ github.repository }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":link: Failed action"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
